name: Sync Files Workflow
on:
  #  push:
  #    branches:
  #      - main
  workflow-dispatch:

jobs:

  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install simple-git
          npm install @octokit/rest
          npm install jsonwebtoken

      - name: Print Secrets
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          GH_APP_PEM_CERT: ${{ secrets.GH_APP_PEM_CERT }}
        run: |
          echo "The GitHub App ID is: $GH_APP_ID"
          echo "The GitHub App Installation ID is: $GH_APP_INSTALLATION_ID"
          echo "The GitHub App PEM Certificate:"
          echo "$GH_APP_PEM_CERT"

      - name: Run Sync Script
        env:
          SOURCE_REPO_URL: ${{ github.event.inputs.source_repo_url }}
          GITHUB_APP_ID: "1083999"
          GITHUB_INSTALLATION_ID_INFRA: "58235263"
          GITHUB_INSTALLATION_ID_SHARED: "58235263" 
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PEM_CERT }}
        #   GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        run: |
            echo "Starting Sync Script..."
            node action/sync_files.js
