name: Test github event
run-name: "Check github event object"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-github-event:
    runs-on: ubuntu-latest
    steps:
      - name: print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
